#############################################################################
# Makefile for building: qip.app/Contents/MacOS/qip
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  qip.pro
# Template: app
# Command: /usr/local/bin/qmake -spec macx-xcode -o project.pbxproj qip.pro
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /usr/local/bin/qmake
project.pbxproj: qip.pro /Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf /Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/qdevice.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/device_config.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/unix.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/mac.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/macx.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/sanitize.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/clang.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/qconfig.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt_config.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/default_pre.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/default_post.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/warn_on.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/resources.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/moc.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/uic.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/exceptions.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/yacc.prf \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/lex.prf \
		qip.pro \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-xcode -o project.pbxproj qip.pro
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/spec_pre.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/qdevice.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/device_config.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/unix.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/mac.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/macx.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/sanitize.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/clang.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/common/clang-mac.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/qconfig.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt_functions.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt_config.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/macx-xcode/qmake.conf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/default_pre.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/resolve_config.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/default_post.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/warn_on.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/qt.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/resources.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/moc.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/uic.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/unix/thread.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/mac/rez.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/exceptions.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/yacc.prf:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/mkspecs/features/lex.prf:
qip.pro:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtPrintSupport.framework/QtPrintSupport.prl:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Linfinity/Qt5.5.1/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-xcode -o project.pbxproj qip.pro

qmake_all: FORCE

